server:
    port: 8080
    session-timeout: 30 # session最大超时时间(分钟)，默认为30

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope: read,write
      auto-approve-scopes: '.*'
      grant-type: password
  basic:
      enabled: false

spring:
    profiles:
        active: dev
    thymeleaf:
        cache: false
        enabled: true
        check-template-location: true
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
        content-type: text/html
        mode: HTML5

    aop:
        auto: true
        proxy-target-class: false