server:
    port: 8080
    session-timeout: 30 # session最大超时时间(分钟)，默认为30

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope: read,write
      auto-approve-scopes: '.*'
      grant-type: password
  basic:
      enabled: false

spring:
    profiles:
        active: dev
    thymeleaf:
        cache: false
        enabled: true
        check-template-location: true
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
        content-type: text/html
        mode: HTML5

    aop:
        auto: true
        proxy-target-class: false
    redis:
      host: 127.0.0.1
      port: 6379
      #database:
      timeout: 15000
      #password:
      pool:
        max-active: 30 # 最大连接数量，默认8，能够同时建立的最大连接数
        max-idle: 20 # 最大空闲连接数量，默认8，空闲连接数大于maxIdle时，将进行回收
        max-wait: 1000 # 最大阻塞等待时间，默认-1
        min-idle: 5 # 最小空闲数，默认0，低于minIdle时，将创建新的连接
